import type { Scenario } from '@/lib/types'

// Exact values from encoder.joblib (verified 2026-03-30, 49 barrier families)
export const BARRIER_TYPES = ['administrative', 'engineering', 'ppe', 'unknown'] as const

export const LINE_OF_DEFENSE = ['1st', '2nd', '3rd', 'recovery', 'unknown'] as const

export const SOURCE_AGENCY_DEFAULT = 'UNKNOWN'

// All 49 barrier families extracted from encoder.joblib
export const BARRIER_FAMILIES = [
  'active_fire_protection_firefighting',
  'active_intervention_to_stop_release',
  'alarms_general_alarm_pa',
  'change_management',
  'chemical_release_scrubbing_neutralization',
  'communication',
  'control_room_habitability_hvac_pressurization',
  'detection_monitoring_alarms',
  'detection_monitoring_surveillance',
  'emergency_disconnect_eds',
  'emergency_escape_access_rescue_decon',
  'emergency_power_backup_utilities',
  'emergency_preparedness_planning_training_drills',
  'emergency_shutdown_isolation',
  'emergency_shutdown_isolation_depressurization',
  'environmental_response_cleanup_reporting',
  'evacuation_muster_shelter_exclusion_access_control',
  'fire_response_firewatch_ignition_control',
  'fluid_discharge_and_containment',
  'gas_detection_atmospheric_monitoring',
  'hazard_analysis_prework_checks',
  'ignition_source_control',
  'incident_command_coordination_and_comms',
  'investigation_corrective_action_post_incident_verification',
  'maintenance',
  'marine_collision_avoidance',
  'mechanical_integrity',
  'medical_response_and_evacuation',
  'monitoring',
  'operating_controls_and_limits',
  'other_admin',
  'other_engineering',
  'other_ppe',
  'other_unknown',
  'overpressurization_gas_discharge_gas_isolation',
  'permits_controlled_work_during_response',
  'physical_protection_retention_restraints',
  'planning',
  'ppe_and_respiratory_protection',
  'pressure_relief_blowdown_flare_disposal',
  'prevention_of_ignition',
  'procedures',
  'regulatory_and_permits',
  'remote_monitoring_intervention_subsea',
  'spill_containment_environmental_mitigation',
  'structural_mechanical_integrity_escalation_prevention',
  'supervision_staffing_oversight',
  'training',
  'well_control_barriers_kill',
] as const

// ---------------------------------------------------------------------------
// Demo scenario (Loss of Containment — LOC)
// 5 prevention + 2 mitigation = 7 barriers.
// Designed for risk spread: engineering barriers score Low, administrative
// barriers (monitoring, procedures) at higher LOD score Medium/High.
// barrier_type/barrier_family use exact encoder values from encoder.joblib.
// ---------------------------------------------------------------------------

export const DEMO_SCENARIO = {
  eventDescription: 'Loss of containment during high-pressure gas transfer operations',
  barriers: [
    {
      name: 'Pressure Relief Valve',
      side: 'prevention' as const,
      barrier_type: 'engineering' as const,
      barrier_family: 'pressure_relief_blowdown_flare_disposal',
      line_of_defense: '1st' as const,
      barrierRole: 'Prevent overpressure beyond design limits',
      pathway_sequence: 0,
      upstream_failure_rate: 0.0,
    },
    {
      name: 'Automatic Shutdown System',
      side: 'prevention' as const,
      barrier_type: 'engineering' as const,
      barrier_family: 'emergency_shutdown_isolation',
      line_of_defense: '1st' as const,
      barrierRole: 'Isolate on high pressure signal',
      pathway_sequence: 0,
      upstream_failure_rate: 0.0,
    },
    {
      name: 'Operator Monitoring Procedure',
      side: 'prevention' as const,
      barrier_type: 'administrative' as const,
      barrier_family: 'monitoring',
      line_of_defense: '3rd' as const,
      barrierRole: 'Manual monitoring of pressure and flow readings during transfer',
      pathway_sequence: 3,
      upstream_failure_rate: 0.7,
    },
    {
      name: 'Pre-Transfer Safety Checklist',
      side: 'prevention' as const,
      barrier_type: 'administrative' as const,
      barrier_family: 'procedures',
      line_of_defense: '2nd' as const,
      barrierRole: 'Verify valve alignment and line integrity before operations',
      pathway_sequence: 2,
      upstream_failure_rate: 0.5,
    },
    {
      name: 'Gas Detection System',
      side: 'prevention' as const,
      barrier_type: 'engineering' as const,
      barrier_family: 'gas_detection_atmospheric_monitoring',
      line_of_defense: '2nd' as const,
      barrierRole: 'Detect gas release in transfer area',
      pathway_sequence: 1,
      upstream_failure_rate: 0.3,
    },
    {
      name: 'Emergency Response Plan',
      side: 'mitigation' as const,
      barrier_type: 'administrative' as const,
      barrier_family: 'emergency_preparedness_planning_training_drills',
      line_of_defense: '1st' as const,
      barrierRole: 'Coordinate emergency response and evacuation',
      pathway_sequence: 1,
      upstream_failure_rate: 0.4,
    },
    {
      name: 'Fire Suppression System',
      side: 'mitigation' as const,
      barrier_type: 'engineering' as const,
      barrier_family: 'active_fire_protection_firefighting',
      line_of_defense: '1st' as const,
      barrierRole: 'Suppress fire from ignited gas release',
      pathway_sequence: 0,
      upstream_failure_rate: 0.0,
    },
  ],
}

// ---------------------------------------------------------------------------
// BSEE demo scenario — matches data/demo_scenarios/bsee_eb-165-a-fieldwood-09-may-2015.json
// Used as raw scenario for the cascading /predict-cascading endpoint (S05a).
// ---------------------------------------------------------------------------

export const BSEE_DEMO_SCENARIO: Scenario = {
  scenario_id: 'bsee_eb-165-a-fieldwood-09-may-2015',
  source_agency: 'BSEE',
  incident_id: 'eb-165-a-fieldwood-09-may-2015',
  top_event: 'Fire from overpressurization and rupture of fuel gas filter vessel',
  context: {
    region: 'Gulf of Mexico',
    operator: 'Fieldwood SD Offshore LLC',
    operating_phase: 'production',
    materials: ['natural gas', 'hydrocarbon fluids', 'glycol'],
  },
  barriers: [
    {
      control_id: 'C-001',
      name: 'Pressure Safety Valve on MBF-V940 Fuel Gas Scrubber',
      barrier_level: 'prevention',
      lod_industry_standard: 'Process Control',
      lod_numeric: 1,
      barrier_condition: 'ineffective',
      barrier_type: 'engineering',
      barrier_role: 'Prevent overpressurization upstream of fuel gas filter',
      linked_threat_ids: ['T-001', 'T-002'],
      description: 'Prevent overpressurization upstream of fuel gas filter',
      line_of_defense: '1st',
    },
    {
      control_id: 'C-002',
      name: 'Pressure Safety Valve on MAK-F960B Fuel Gas Filter',
      barrier_level: 'prevention',
      lod_industry_standard: 'Structural Integrity',
      lod_numeric: 2,
      barrier_condition: 'ineffective',
      barrier_type: 'engineering',
      barrier_role: 'Prevent overpressurization of fuel gas filter vessel',
      linked_threat_ids: ['T-001', 'T-002'],
      description: 'Prevent overpressurization of fuel gas filter vessel',
      line_of_defense: '2nd',
    },
    {
      control_id: 'C-003',
      name: 'Vessel structural integrity and corrosion management',
      barrier_level: 'prevention',
      lod_industry_standard: 'Structural Integrity',
      lod_numeric: 1,
      barrier_condition: 'ineffective',
      barrier_type: 'engineering',
      barrier_role: 'Maintain vessel pressure rating through corrosion prevention',
      linked_threat_ids: ['T-003'],
      description: 'Maintain vessel pressure rating through corrosion prevention',
      line_of_defense: '1st',
    },
    {
      control_id: 'C-004',
      name: 'Differential pressure gauges on fuel gas filters',
      barrier_level: 'prevention',
      lod_industry_standard: 'Alarm and Operator Response',
      lod_numeric: 2,
      barrier_condition: 'ineffective',
      barrier_type: 'engineering',
      barrier_role: 'Provide operator indication of filter element condition and need for replacement',
      linked_threat_ids: ['T-001'],
      description: 'Provide operator indication of filter element condition and need for replacement',
      line_of_defense: '2nd',
    },
    {
      control_id: 'C-005',
      name: 'Level Safety High (LSH) and Sight Glasses on fuel gas filters',
      barrier_level: 'prevention',
      lod_industry_standard: 'Alarm and Operator Response',
      lod_numeric: 2,
      barrier_condition: 'degraded',
      barrier_type: 'engineering',
      barrier_role: 'Provide accurate indication of fluid level in filter vessels',
      linked_threat_ids: ['T-001'],
      description: 'Provide accurate indication of fluid level in filter vessels',
      line_of_defense: '2nd',
    },
    {
      control_id: 'C-006',
      name: 'Single-stage pressure reduction system',
      barrier_level: 'prevention',
      lod_industry_standard: 'Structural Integrity',
      lod_numeric: 1,
      barrier_condition: 'degraded',
      barrier_type: 'engineering',
      barrier_role: 'Reduce inlet pressure from 945-1290 PSI to safe operating pressure',
      linked_threat_ids: ['T-001'],
      description: 'Reduce inlet pressure from 945-1290 PSI to safe operating pressure',
      line_of_defense: '1st',
    },
    {
      control_id: 'C-008',
      name: 'Emergency response and fire suppression equipment',
      barrier_level: 'mitigation',
      lod_industry_standard: 'Protection Systems',
      lod_numeric: 4,
      barrier_condition: 'effective',
      barrier_type: 'engineering',
      barrier_role: 'Extinguish fire and limit consequences',
      linked_threat_ids: ['T-004'],
      description: 'Extinguish fire and limit consequences',
      line_of_defense: 'recovery',
    },
  ],
  threats: [
    { threat_id: 'T-001', name: 'Overpressurization of fuel gas filter vessel', description: null },
    { threat_id: 'T-002', name: 'Failure of pressure safety valves to relieve at set pressure', description: null },
    { threat_id: 'T-003', name: 'Structural failure of corroded vessel', description: null },
    { threat_id: 'T-004', name: 'Ignition of released fuel gas', description: null },
  ],
  pif_context: {
    people: { situational_awareness: true },
    work: { procedures: true, tools_equipment: true },
    organisation: { safety_culture: true, management_of_change: true },
  },
}
